### ISSUE TITLE
Fail to AutoStart the software

### ISSUE THREAD

**Issue by ForestL18** [sidit77/rusty-twinkle-tray#4]
Hi, rusty-twinkle-tray is a faster and lighter tool, comparing with the electron one, I appreciate it more.

There is an issue of AutoStart function, I've tried some ways to solve the problem, but it's not working.

1. Using the autostart function of the software. Whether normal or higher priority, when the PC restart or wake from sleep, the software is not starting as expected.
2. Using the Windows schedule task. If it is set to run as normal priority, just like above, not auto starting; if it is set to run as highest priority, it will throw out an error below.

![image](https://github.com/user-attachments/assets/225f6763-6d6c-49c4-b663-ccd829644ce5)

**Comment by sidit77** [comment]
Can you see the program in the taskmanager when you enable autostart withing the settings windows?
![image](https://github.com/user-attachments/assets/84efe05b-df03-4c0d-a726-3ab0018dfb63)

**Comment by sidit77** [comment]
Its really strange, all the autostart option does is add an registry key with the path to the current exe to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` (or `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` if high priority is enabled).

Is there a space or something in the path to the exe file? Maybe the path needs to be quoted?
Or is there maybe a Chinese character in the path? I tried to always stick to unicode but I havn't tested any non-latin characters either.

Can you use `regedit` to find the entry and check (e.g with Win + R) if the autostart command works if you invoke it manually?

**Comment by sidit77** [comment]
The underscore is intentionally there, because Windows seems to process the entries in alphabetical order. 

I can't really think of anything else that could go wrong the autostart tbh.  You could try to place the exe or a shortcut to it into `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` and see if that works.

**Comment by sidit77** [comment]
> But there's also a problem, when I wake my PC from sleep or hibernation, RustyTwinkleTray can't autostart, maybe need fix.

I'm not sure that I fully understand the issue. When you put your PC to sleep all open programs should still be open after you wake your PC up again and no autostart should be needed. Is this not the case for you?

**Comment by sidit77** [comment]
This clarifies the issue. I'll try to reproduce the issue once I find the time to do so.

**Comment by sidit77** [comment]
I pushed a commit (e0112eb785764dd356b4b834a13db78053726b94), which should hopefully fix your issue.

**Comment by sidit77** [comment]
I just pushed another commit. I figured out that waking your PC from sleep mode will send a specifc message to all windows that I was handling wrong.
